---
booktitle: 'Proceedings of the Third International Workshop on Learning with Imbalanced
  Domains: Theory and Applications'
shortname: LIDTA
sections:
- name: Preface
  title: Preface
- name: Papers
  title: Papers
year: '2021'
volume: '154'
start: 2021-09-17
end: 2021-09-17
published: 2021-09-29
url: https://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: LIDTA2021
month: 0
cycles: false
bibtex_editor: Moniz, Nuno and Branco, Paula and Torgo, Luis and Japkowicz, Nathalie and Wo\'zniak,
  Micha\l and Wang, Shuo
editor:
- given: Nuno
  family: Moniz
- given: Paula
  family: Branco
- given: Luis
  family: Torgo
- given: Nathalie
  family: Japkowicz
- given: Michał
  family: Woźniak
- given: Shuo
  family: Wang
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Third International Workshop on Learning with Imbalanced Domains: Theory and Applications
    Held in ECML-PKDD, Bilbao (Basque Country, Spain) on 17 September 2021

  Published as Volume 154 by the Proceedings of Machine Learning Research on 29 September 2021.

  Volume Edited by:
    Nuno Moniz
    Paula Branco
    Luis Torgo
    Nathalie Japkowicz
    Michał Woźniak
    Shuo Wang

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 17 Sep
author:
  name: PMLR
baseurl: "/v154"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v154
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v154
email: ''
conference:
  name: 'Third International Workshop on Learning with Imbalanced Domains: Theory
    and Applications'
  url:
  location: ECML-PKDD, Bilbao (Basque Country, Spain)
  dates:
  - 2021-09-17
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v154/LIDTA21.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v154/LIDTA21.bib
